### ISSUE TITLE
1.13 Error al iniciar servidor

### ISSUE THREAD

**Issue by ghost** [rmaafs/ArenaPvP-Plus#1]
## Error cuando se inicia el servidor.

```java

**ArenaPvP+ > Detected v1_13_R1 version**.

_[ERROR] Error occurred while enabling ArenaPvP v1.2.1 (Is it up to date?)

java.lang.NoSuchMethodError: org/bukkit/inventory/ItemStack.<init>(IIS)V (loaded from file:/pro/bin/mc/spigot/1.13/spigot-1.13.jar by sun.misc.Launcher$AppClassLoader@10238784) called from class com.rmaafs.arenapvp.Extra (loaded from file:/home/gs-40308/plugins/ArenaPvP-1.2.1.jar by org.bukkit.plugin.java.PluginClassLoader@62d9207c).

at com.rmaafs.arenapvp.Extra.crearId(Extra.java:433) ~[?:?]

at com.rmaafs.arenapvp.Juegos.Duel.DuelControl.setConfig(DuelControl.java:84) ~[?:?]

at com.rmaafs.arenapvp.Juegos.Duel.DuelControl.<init>(DuelControl.java:47) ~[?:?]

at com.rmaafs.arenapvp.Main.onEnable(Main.java:137) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]

at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]

at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]

at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]

at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]

at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]

at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]

at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]

at java.lang.Thread.run(Thread.java:823) [?:1.8.0_272]_
```

**Comment by rmaafs** [comment]
Gracias por tu reporte, lo estaré revisando.

**Comment by cumhilo** [comment]
Is it already solved?
